# Site settings
title: Ian Maddaus
email: spamforian@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This is what interests me or what I'm working on.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ianmadd.github.io" # the base hostname & protocol for your site
twitter_username: ianmaddaus
github_username:  IanMadd
categories: [R_Programming, subsetting_data, transforming_data, plots_and_graphics, functions]

# Build settings
markdown: kramdown
